</$objtype/mkfile

TARG = libraries \
		exported \
		functions \
		multiple-returns \
		variables \
		variables-with-inits \
		basic-types \
		zero \
		type-conversions \
		constants \
		numeric-constants \

</sys/src/cmd/mkmany
